sudo: required
services:
    - docker

before_install:
    - docker build -t moideenluqman/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true moideenluqman/docker-react npm run test -- --coverage
