sudo: required
services:
    - docker

before_install:
    - docker build -t moideenluqman/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true moideenluqman/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-app"
    env: "DockerApp-env"
    bucket_name: "elasticbeanstalk-us-east-2-485542349203"
    bucket_path: "docker-app"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
